package chat.webside.interactive.model;

import java.util.Map;

public class InteractiveMessage {

    /**
     * to avoid any incompabilities with different browsers etc. we put the
     * whole JSON message generated by the browser's WebRTC implementation in
     * one String *
     */
    private Map<String, Object> message;
    /**
     * WebRTC data *
     */
    private String type;
    /**
     * Used in the Java-Script application *
     */
    private String fromUserID;
    /**
     * should be always filled with the correct principal *
     */
    private String toUserID;

    /**
     * mandatory only for signaling messages *
     */


    public Map<String, Object> getMessage() {
        return message;
    }

    public String getType() {
        return type;
    }

    public String getFromUserID() {
        return fromUserID;
    }

    public void setFromUserID(String fromUserID) {
        this.fromUserID = fromUserID;
    }

    public String getToUserID() {
        return toUserID;
    }

}
